version: "3.7"
services:
  web-server:
    # image: node:18
    build:
      context: ./src
      dockerfile: docker/Dockerfile
    working_dir: /app/
    environment:
      APP_SHORTEN_DOMAIN: http://localhost
      APP_PORT: 3005
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: FB66c57VK
      DATABASE_USERNAME: root
    volumes:
      - ./src:/app
    ports:
      - "3005:3005"
    command: "npm run start:dev"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: FB66c57VK
    ports:
      - "3307:3306"

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web-server
