apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      # targetPort: expose by a pod or deployment. Port: port from host machine
      port: 80
      protocol: TCP
      targetPort: 3005
      